#! /bin/sh
# just shows `opened` files ala `p4 opened`
#   -1 lists all files on one line (subject to the xargs line length limit)

append=""
usage() { echo "Usage: $0 [-1]" 1>&2; exit 1; }

while getopts "1" opt; do
  case "${opt}" in
    1) append='| xargs' ;;
    *) usage ;;
  esac
done

eval "git status --short | cut -c 4- $append"
